mysql code

diff --git a/.github/workflows/sql-ci.yml b/.github/workflows/sql-ci.yml
--- a/.github/workflows/sql-ci.yml
+++ b/.github/workflows/sql-ci.yml
@@ -22,6 +22,20 @@ jobs:
         with:
           mysql-version: '8.0'
       - run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
+      - name: Setup Data
+        run: |
+          mysql -u root  -h127.0.0.1 < schema.sql
+          mysql -u root  -h127.0.0.1 < data.sql
+
+      - name: Run tests
+        run: |
+          mysql -u root  -h127.0.0.1 < tests.sql
+          
+          # Check the output of tests and fail the build if necessary
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Aborting deployment."
+            exit 1
+          fi
 
       # - name: Shutdown Ubuntu MySQL (SUDO)
       #   run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
